### ISSUE TITLE
help me i can't see my estimated mmr

### ISSUE THREAD

**Issue by despicable1** [odota/ui#1055]

**Comment by howardchung** [comment]
Link to profile?  Most probable cause is that you haven't played any matches with any players showing their MMR.

**Comment by despicable1** [comment]
https://www.opendota.com/players/441879865

**Comment by despicable1** [comment]
do you have a fb page?? or fb account

**Comment by blukai** [comment]
@despicable1 everyone in ur 5 matches haven't showing their mmr, so it can't be calculated.
MMR estimate based on the mean visible MMR of the recent matches played.

---

On top-right of match page u can see 

![image](https://user-images.githubusercontent.com/20866892/27787937-414b2ea8-5fef-11e7-9a4b-d20e43bbbcb2.png)

Unknown since possibly everyone in ur matches has new accounts, or haven't showing their mmr.

Personal mmr if it was shown, displayed here

![image](https://user-images.githubusercontent.com/20866892/27788044-b9e76822-5fef-11e7-98c8-d925a3a20a71.png)

**Comment by despicable1** [comment]
so how can i get my estimated mmr ???

**Comment by despicable1** [comment]
my friend said  that  when he using his yasp account and played 2 games his estimated mmr come up ?

**Comment by despicable1** [comment]
kindly give me a tip or maybe my setting is in private mode ,,, help me admin,,  T_T

**Comment by blukai** [comment]
When u'll get someone in match, who showing their mmr, ( @howardchung, I guess that one player, who showing mmr is enough? ) it will come up. So just play and have fun 😛

**Comment by despicable1** [comment]
thank you
