### ISSUE TITLE
Add OpenAI to sponsors list

### ISSUE THREAD

**Issue by howardchung** [odota/ui#1277]
OpenAI recently donated $12,000 to the project.

We should add their logo to our sponsors list on the home page.

https://openai.com

**Comment by terenceponce** [comment]
I'm on this right now. Unfortunately, it looks kind of bad because it looks too small compared the rest of the logos.

<img width="854" alt="screen shot 2017-10-25 at 9 28 19 am" src="https://user-images.githubusercontent.com/376472/31975952-17bc53a6-b967-11e7-9a15-48cb134da5ea.png">

I'll try to find other logos that we can use. The one in the screenshot is from their official site.

**Comment by imwally** [comment]
Oh, @terenceponce  that was quick!

I had the same issue but I was able to find a more horizontally aligned logo in black which I inverted to white.

<img width="946" alt="screen shot 2017-10-24 at 9 38 14 pm" src="https://user-images.githubusercontent.com/129967/31976170-d4af2d94-b903-11e7-863c-d7323f9ebea3.png">

**Comment by terenceponce** [comment]
@imwally yours is better. I also went through the same thing, but you beat me to the punch.

<img width="948" alt="screen shot 2017-10-25 at 9 44 33 am" src="https://user-images.githubusercontent.com/376472/31976290-35f492d2-b969-11e7-9a38-1fb3718dc3bb.png">


You should do the honor of creating the PR for this.
