### ISSUE TITLE
add removed item data to dotaconstants data files

### ISSUE THREAD

**Issue by howardchung** [odota/ui#1302]
Related to the issue reported here:
https://www.reddit.com/r/DotA2/comments/7b7b5b/open_dota_bug_with_the_builds_showing_spirit/?st=j9p6qj0z&sh=a3e98d71

Diffusal blade 2 has been removed from the game and therefore isn't in the game client files anymore.  We need to update the dotaconstants update script to manually put these items back into the the data files:
* poor man's shield
* iron talon
* diffusal blade 2

Otherwise, these items won't show up at all for older matches.

**Comment by mandyMooreFan** [comment]
PMS and Iron Talon both appear to be working.  It seems only diffBlade2 is the issue.  In the match linked on reddit you can see PMS and Iron Talon shown properly on the purchase screen (https://www.opendota.com/matches/3354544275/purchases). 

In dotaConstants what is the purpose of relying on?:
https://raw.githubusercontent.com/dotabuff/d2vpkr/master/dota/scripts/npc/items.json

DotaBuff doesn't worry about this, because they still display the image and just let the tooltip error.  
![image](https://user-images.githubusercontent.com/3291445/32623901-a3817886-c555-11e7-8c89-30780d4b20e8.png)

Would you like to still rely on dotabuff's items.json and change how the images are generated?  Or stop relying on that to generate the items json.

*Sorry if I missed something easy on this.

**Comment by howardchung** [comment]
Basically, in the update script we should manually insert the diffusal_blade_2 blob which is in a previous version of the items data, like: https://github.com/odota/dotaconstants/blob/b759330db327efa7e63bcfc0ec00bacfaffbf0e8/build/items.json#L7152

It also needs to be manually added to item_ids.json

That should fix both the image and the tooltip.
