### ISSUE TITLE
I18N support for heroes and items.

### ISSUE THREAD

**Issue by kxxoling** [odota/ui#411]
I guess I can add other language like Chinese support by creating a new `zh.js` in `src/lang`. But it seems not supporting heroes names translation.

**Comment by howardchung** [comment]
That's because this data is from the Dota 2 site:
http://www.dota2.com/jsfeed/itemdata

We can get other languages with something like the following:
http://www.dota2.com/jsfeed/itemdata?l=schinese

However we don't want to bundle all the other languages into the JS bundle so we need to rethink how we load tooltip data.

**Comment by kxxoling** [comment]
So is this a considering feature?

**Comment by howardchung** [comment]
I'd like to do it at some point but it requires a code change to how we get the tooltip data.

**Comment by howardchung** [comment]
merge with #338
