### ISSUE TITLE
show top peers on overview

### ISSUE THREAD

**Issue by howardchung** [odota/ui#429]

**Comment by bill-mavromatis** [comment]
Really looking forward to this one!

**Comment by mike-robertson** [comment]
@blukai @howardchung do you guys have any preference on how we display this data? I'm thinking we could try putting it above heroes so the new screen looks like matches on the left, peers/heroes on the right. Idk what we want to show for peers though (recent games with them?)

**Comment by howardchung** [comment]
Yeah I think we'd just show the top 20 peers (making the same /peers API call as the peers tab and limiting the display, like we do with heroes).

I suppose we'd want the column for games with+games_against.  Should we stack them?  Maybe 10 heroes/10 peers to make it balance matches?

**Comment by covertPZ** [comment]
I just started working on this and having them stacked on the right. If we have it pull 10 heroes/10 peers it will still look off due to the container titles and the table headers. Maybe we got with top 5 peers instead of 10?

Option 1 (20 Matches, 10 Heroes, 10 Peers):
![ss 2017-01-08 at 03 40 26](https://cloud.githubusercontent.com/assets/1359826/21753325/ea242640-d5b8-11e6-90b2-8c083eecc28c.jpg)

Option 2 (20 Matches, 10 Heroes, 5 Peers):
![ss 2017-01-08 at 03 44 10](https://cloud.githubusercontent.com/assets/1359826/21753348/4e2aff9c-d5b9-11e6-8643-a440f1325b7c.jpg)

Option 3 (20 Matches, 5 Peers, 10 Heroes):
![ss 2017-01-08 at 03 44 52](https://cloud.githubusercontent.com/assets/1359826/21753354/719f2f66-d5b9-11e6-924b-f35a9097867a.jpg)

Personally I like option 3 the best. Putting Peers above Heroes lets you see that there's more info on load, otherwise the Peers section is pushed far enough down on the page that you won't see it till you scroll down a few rows.
