### ISSUE TITLE
Multiple purchases of the same item show wrong timings on overview

### ISSUE THREAD

**Issue by chudooder** [odota/ui#437]
https://www.opendota.com/matches/2762021523/overview

Both Daedalus are marked at 26:08. The Purchases tab correctly shows the second one being purchased at 53:02.

**Comment by jfo84** [comment]
I'm taking a look at this one

**Comment by howardchung** [comment]
This one's a bit tricky.  On the server side, before sending over the match JSON, we go through the purchase log of each player and map item key to the first time that it was purchased.  This is what we use on the client side to display the time.  Since it's just a "first purchase" time, the same item id showing up repeatedly leads to the same time being shown.

We CAN iterate over the purchase log again per player to catch purchases after the first, but it might be simpler just to omit the display if it's been shown once already.

**Comment by howardchung** [comment]
Anything we do on the server side we can do on the client side.  So anything we do there we can do on the client side, we just have to make it's not overly slow so it doesn't hold up page rendering.

This is how we do it on the server side:
https://github.com/odota/core/blob/master/util/compute.js#L177

**Comment by jfo84** [comment]
Line 167 actually. Updated the comment

**Comment by jfo84** [comment]
Okay I see. Makes sense to me. I'll see how it feels, but I'm leaning toward just giving it a UI treatment if it's a duplicate since that stat also powers the late courier upgrade stat on the analysis tab
