### ISSUE TITLE
Profile not showing any information, giving the Whoops! Something went wrong error.

### ISSUE THREAD

**Issue by DickArmy** [odota/ui#631]
I'm getting the following error for over a week when trying to access my profile at https://www.opendota.com/players/102984233: **Whoops! Something went wrong.** This is my steam https://steamcommunity.com/id/N_Bourbaki. My profile is showing zero information and I've tried relogging through steam several times.
- **OS**: Microsoft Windows 10 Home 64 bit
- **Screen Resolution**: 1920 x 1080
- **Browser/Version**: Chrome Version 55.0.2883.87 m
- **Link to page with the issue, or screenshot**:![opendota](https://cloud.githubusercontent.com/assets/574829/21465203/ec7df5c0-c9be-11e6-9bd6-8ef74872a2cb.png) https://www.opendota.com/players/102984233

**Comment by howardchung** [comment]
Did this only start last week and worked fine before?

**Comment by DickArmy** [comment]
> @howardchung Yes, It has worked fine for several months. Issue only started around a week ago. Ive tried Int explorer too same issue.

**Comment by howardchung** [comment]
Can you follow the steps described here so we can see if your console is outputting any errors?

https://github.com/odota/ui/issues/544

**Comment by DickArmy** [comment]
![od1](https://cloud.githubusercontent.com/assets/574829/21466458/2d4d93ce-c9f3-11e6-8382-4e3df9789332.png)

**Comment by DickArmy** [comment]
![od2](https://cloud.githubusercontent.com/assets/574829/21466810/f45dcb5c-c9fb-11e6-9d15-539e74688d2e.png)
![od3](https://cloud.githubusercontent.com/assets/574829/21466812/f669e872-c9fb-11e6-9374-43de4bd278fc.png)

**Comment by DickArmy** [comment]
Also I've been getting the cloudflare captcha on a lot of websites since last week, od included. And I've made my mmr public and permanently enabled "expose public match data". Individual match parsing requests also give an error.

**Comment by howardchung** [comment]
OK, I suspect this is a cloudflare issue then/  I changed the "security level" setting to essentially off as described here: https://support.cloudflare.com/hc/en-us/articles/200170096-How-do-I-turn-the-CloudFlare-captcha-challenge-page-off-

A brief explanation: OpenDota (the web version) is now basically just a bunch of javascript calls that makes API calls to the opendota API.  We use cloudflare (like many other sites) to help with caching and reduce traffic costs, but if for some reason cloudflare is blocking or requiring captchas for the API calls, the site will fail to show any data or request a parse (since it can't contact the API).  This has nothing to do with the public match data setting or showing MMR on your profile.

**Comment by DickArmy** [comment]
Everything seems to be back to normal now. Is there anything I can do from my side to stop cloudflare from interfering again in the future if you decide to revert back the settings?

**Comment by howardchung** [comment]
No, this is a server side issue.  I'm fine leaving the security setting as is.  It's just a form of DDOS protection (I think cloudflare puts up the captcha for IP origins it determines to have a history of suspicious behavior, but this can false positive if people are sharing IP pools etc.)

Re: MMR, have you played a ranked game since showing it?  We don't poll for MMR, we only trigger an update when a player finishes a ranked match.

**Comment by DickArmy** [comment]
Only played unranked since making it public. Will get back if it doesn't update after a ranked game. Thanks!
