### ISSUE TITLE
Search bar is really slow when on a player or match page

### ISSUE THREAD

**Issue by masad-frost** [odota/ui#745]
Typing is so janky, probably a performance issue

**Comment by masad-frost** [comment]
Just tried adding a normal `<input value={this.state.input} onChange={e => this.setState({ input: e.target.value})}/>` field on the same page and it's also really slow.

**Comment by howardchung** [comment]
I think this is due to the "dispatchSetQuery" that occurs after each keystroke.  I don't know if React is trying to redraw more than it should.  Perhaps we can cache the state in the local component state in searchField and only fire dispatchSetQuery to update the Redux store when the form is finally submitted?

**Comment by blukai** [comment]
http://stackoverflow.com/questions/23123138/perform-debounce-in-react-js
