### ISSUE TITLE
"Open link in new tab" redirect issue

### ISSUE THREAD

**Issue by WA4** [odota/ui#756]
[I recorded a gif to demonstrate the problem](http://i.imgur.com/CJx0oCg.gifv)

I am used to opening a lot of links with my scroll button, and then tabbing through them. Having to press "Allow" on every redirect request is **extremely** clunky.

**Comment by howardchung** [comment]
This seems like a default feature on Firefox and can be disabled?

https://support.mozilla.org/t5/Firefox-for-iOS/Firefox-prevented-this-page-from-automatically-redirecting-to/m-p/1279109

**Comment by WA4** [comment]
I'd prefer to leave the option on, since I've encountered malicious redirects in the past.

I tried looking for a setting that lets me allow exceptions for certain websites, but I didn't find one.

**Comment by howardchung** [comment]
I'm not sure this can be fixed on the server side since currently the UI relies on GitHub Pages' custom 404 page to send the user back to index.html which runs the javascript bundle.

A potential option is to make the 404.html a copy of index.html so it runs the bundle without the redirect, but this may be bad for SEO as search engines see it as a 404 result rather than a 302 redirect.

**Comment by howardchung** [comment]
Switched to serving the page out of https://www.netlify.com/ rather than GitHub pages.  They have an option to return a 200 with index.html rather than relying on the 404 hack, so this issue should be resolved :)
