### ISSUE TITLE
Player search 

### ISSUE THREAD

**Issue by arielg81** [odota/ui#762]
The player search does not work with names that contain the character < at start.
 Windows 10
1920x1080
Chrome Versión 56.0.2924.87

**Comment by howardchung** [comment]
Do you have an example player with a name starting with `<`?

**Comment by arielg81** [comment]
<Acolyte >
Probably not registered

**Comment by howardchung** [comment]
Do you have the account_id for this player?

**Comment by arielg81** [comment]
150570654

**Comment by howardchung** [comment]
It looks like the player's name is saved as `< Hann >`.

https://www.opendota.com/players/150570654

The last match is from 10 months ago.  We randomly update names from players who have recently played matches, so that's probably why it's not updated.

**Comment by arielg81** [comment]
Well, that's a good example. Try to find `< Hann >` with Player Search.

**Comment by howardchung** [comment]
The problem is that the substring is too common and search limits to 500 results by default.

The default similarity threshold is 0.4, so if there are more than 500 results with a similarity of 0.4 or greater, the desired player may not be found.

The API allows cranking up the similarity threshold, so you can see that if we pass a high value, it'll find it:
http://api.opendota.com/api/search?q=%3C%20Hann%20%3E&similarity=0.9

We can bump up the default value, but we don't want to make it too high or else results we want might be excluded.

Looks like a value of 0.51 excludes most of the matches, so I'll try that out.
