### ISSUE TITLE
Trends should be averaged per week/month/patch/moving mean

### ISSUE THREAD

**Issue by previsualconsent** [odota/ui#849]
Instead of showing how the average changes with more games which just has winrate converge on 50% usually, it would be nice to see the actual trend. 

For example: if you want a trend of GPM, you would average gpm of all matches in a time window.
For ease of coding, you could even just average 10-20 consecutive games regardless of match time. 

This way one could tell how much their _data_ has fluctuated over time instead of just get a more more and more accurate average.

**Comment by howardchung** [comment]
Could try it out and see how it looks.  I'm worried that the "buckets" of 10 matches will be affected by outliers.

**Comment by previsualconsent** [comment]
Could put error bars on it.

**Comment by rafd** [comment]
:+1:

I suggest using an [exponential moving mean](https://en.wikipedia.org/wiki/Exponential_smoothing). 

If you approve, I can submit a PR.

Below I describe a few alternatives to showing trends in graphs. I've graphed the same data, my LH/10, which tends to vary a lot between games.  _Pay particular attention to the streak of low scoring games in the middle followed by a few big outliers._

Notice how the cumulative mean graph is pretty much useless vs. any of the other approaches.

Any of the alternatives is a significant improvement over the current approach. In practice, the differences between the others are minor. 



--------


## A. Cumulative Mean

<img width="656" alt="screenshot 2017-04-24 14 15 44" src="https://cloud.githubusercontent.com/assets/89664/25352321/a6f975d4-28f9-11e7-8eb1-415156c9fb65.png">

The current implementation. Doesn't actually show 'trends' (just shows 'convergence to mean' given any data). Data is pretty much a straight line.

```graph(i) = sum(game(0)...game(i)) / i```
 
Cons:

  - data always looks the same (ups and downs then converge to average)
  - initial games affect the graph, but later games have little effect
  - only a significant and sustained change will alter the graph
  - can't detect recent trends

## B. Moving Mean

<img width="662" alt="screenshot 2017-04-24 14 15 26" src="https://cloud.githubusercontent.com/assets/89664/25352425/f7ef0ab2-28f9-11e7-95e2-cf407a1324d3.png">

Average of the last N games. 

```graph(i) = sum(game(i-range)...game(i)) / range```

Pros:

  - actually shows trends
 - weight parameter can be adjusted (could even do it dynamically in the UI)

Cons:

  - only takes into account recent games (within the 'range')
  - affected by short-term outliers
  - first few data points (within the 'range') need to follow a different rule (or be omitted)


## C. Moving Median

<img width="660" alt="screenshot 2017-04-24 14 15 50" src="https://cloud.githubusercontent.com/assets/89664/25352290/92183934-28f9-11e7-9309-d99916a17004.png">

```graph(i) = median(game(i-range)...game(i))```

Pros:

  - actually shows trends
  - less affected by outliers than Moving Mean
  - range parameter can be adjusted (could even do it dynamically in the UI)

Cons:

  - only takes into account recent games (within the 'range')
  - can't be used for Win %  (b/c it would just be 0 or 1)
  - first few data points (within the 'range') need to follow a different rule (or be omitted)


## D. Exponential Moving Mean

<img width="656" alt="screenshot 2017-04-24 14 15 34" src="https://cloud.githubusercontent.com/assets/89664/25352430/ffb53c58-28f9-11e7-9faf-e9a13dc3d023.png">

Similar to the moving average, but weighs recent games more than older games (rather than equally). Ex. if 10% is chosen as the `r` parameter below, the most recent game would have 10% impact, the next game would be 9%, then: 8.1%, 7.3%, 6.6%, 5.9% ....

```graph(i) = graph(i-1)*(1-r) + data(i)*r``` 
(where r is the ratio of the most recent game to previous games, a value between 0 and 1, suggested around 0.05 - 0.5)

Pros:
  - actually shows trends
  - _takes into account both long-term data and recent data_
  - can use same rule for initial values (although data is more chaotic)
  - weight parameter can be adjusted (could even do it dynamically in the UI)
  - can use for Win %
  - still easy to calculate



## Summary

Method | Cumulative Mean | Moving Mean | Moving Median | Exponential Moving Mean
-- | -- | -- | -- | --
Shows Meaningful Trends |   | ✓ | ✓ | ✓
Can use for Win %, and others | ✓ | ✓ |   | ✓
Susceptibility to Outliers | ★★★ | ★☆☆ | ★★★ | ★★☆

**Comment by previsualconsent** [comment]
Sure. Histograms have the benefit of selected different binning methods. You could bin by week/month/year/patch

and it has the simplicity that a user doesn't need to ask "what does this line mean?"  its just the average for that bin.

**Comment by howardchung** [comment]
@rafd thanks for the detailed analysis!  Exponential moving mean sounds good to me, I'd love to see a PR.

Did you try drawing a graph for "bins" trend as well?  I guess it would be similar to the moving mean approach, but discrete rather than continuous.

**Comment by howardchung** [comment]
Moving mean with a larger N (30?) might also reduce the effect of outliers while being easier for the layperson to understand.

**Comment by previsualconsent** [comment]
Example of binned by 30 games

![kda_hist](https://cloud.githubusercontent.com/assets/705855/25403359/b584ce3c-29c1-11e7-8824-3f39c4e90c27.png)
