### ISSUE TITLE
Missing/incorrect image key for tornado/tempest

### ISSUE THREAD

**Issue by howardchung** [odota/ui#993]
https://www.opendota.com/matches/3223740175/combat (see Enchantress damage dealt)

**Comment by sams-joseph** [comment]
The constant in the NPM module dotaconstants' neutral_abilities for this ability is `enraged_wildkin_tornado`. However the key returned from the Steam API is `tornado_tempest`. So you parse the img src as if it is an `ability` and not a `neutral_ability` because it fails the conditional. Renamed the constant in my local npm_modules and this solved the issue.

**Comment by howardchung** [comment]
So just a quick pull request to dotaconstants to correct the string should fix this?

**Comment by sams-joseph** [comment]
Created pull request with change.

**Comment by howardchung** [comment]
Doesn't seem to be fixed in prod, will investigate further.

**Comment by sams-joseph** [comment]
I just updated my forked repo from the master branch for the UI and after doing a fresh `npm install` locally to update dotaconstants the problem was resolved.

**Comment by howardchung** [comment]
It looks like with the introduction of `package-lock.json` in npm5, minor/patch updates will not be updated in downstream packages.

I've run `npm update` to update the lockfile and the change should be reflected in the next release.

cc @Crazy-Duck
